/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersNameRouteImport } from './routes/players.$name'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersNameRoute = PlayersNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => PlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/players': typeof PlayersRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/players/$name': typeof PlayersNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/players': typeof PlayersRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/players/$name': typeof PlayersNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/players': typeof PlayersRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/players/$name': typeof PlayersNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/players' | '/sitemap.xml' | '/players/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/players' | '/sitemap.xml' | '/players/$name'
  id: '__root__' | '/' | '/players' | '/sitemap.xml' | '/players/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$name': {
      id: '/players/$name'
      path: '/$name'
      fullPath: '/players/$name'
      preLoaderRoute: typeof PlayersNameRouteImport
      parentRoute: typeof PlayersRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersNameRoute: typeof PlayersNameRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersNameRoute: PlayersNameRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayersRoute: PlayersRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
